apiVersion: omf.dev/v1alpha1
kind: EvaluationSpec
metadata:
  name: example-affine
  namespace: local/open-model-factory
spec:
  protocol: omf.evaluation/v1
  metrics:
    - name: training-loss
      output: train.loss
      maximum: 0.000001
    - name: parameter-check
      output: evaluate.passed
      minimum: 1.0
  data: []
  inferencePolicy:
    compatibility: model-package
